---
- hosts: all
  strategy: debug
  tasks:
    - name: test debug
      command: echo 1
    - include: tasks/foo.yml
  handlers:
    - name: restartsyslog
      become: yes
      become_user: root
      become_method: su
      service:
        name: rsyslog
        state: reloaded

