- set_fact: 
    pepe: "jeronimo garcia"

- name: "common task following"
  command: echo {{ hostvars.keys() }} 
  with_items: "{{ groups['all']}}"
  register: pepe

- name: "fake loop"
  command: echo {{ item }}
  with_lines: grep jegarcia /etc/passwd   

- name: "daddasda33a"
  command: echo {{pepe}}


- name: "replacing test"
  lineinfile:
    dest: /home/jegarcia/Projects/ansible2/testfile
    regexp: "{{ item.regexp }}"
    line: "{{ item.line}}"
  with_items:
    - { regexp: 'dog' ,  line: 'Dog' }
    - { regexp: 'cat' ,  line: 'Cat' }
- name: "test replce simple"
  replace:
    dest: /home/jegarcia/Projects/ansible2/testfile
    regexp: "{{ item.reg }}"
  with_items:
    - { reg: 'Dog,pepe' }
    - { reg: 'Cat,pepe' }

      
- debug:
    #msg: "{{ pepe['results'] }}"
    msg: "{{ hostvars[inventory_hostname]['ansible_version']['full']}}"
##when: 
  ##- ct['rc'] == 0
  ##- " [ct['stdout'].rfind('h')] == map(lambda x: 0 if x == 0 else 1 , [0] )"
  ##- " [ct['stdout'].rfind('h')]|length == 1  "
  ##- " ct['stdout'] == 0 "
  ##- " 1 in [1,2,3,4] "
    #- "{{ groups['all'] }} "
    ##- " {{ ansible_all_ipv4_addresses }} "
    ##- [1,2]
    #register: output
    #- debug:
      #msg: 
        ##- "{{ct['stdout']}}"
        ##- " {{ hostvars['127.0.0.1']['ansible_connection']['local'] }}"
        ##- " {{ hostvars[inventory_hostname] }} "
        ##- " {{ groups['all'] }} "
        ##- " {{ output }} "
        #- " {{ groups['all'] }} "
