- set_fact: 
    pepo: "jeronimo garcia"
    register: pepo
- debug: 
    msg: "eoooo {{ pepo }}"
- name: "common task following"
  command: echo {{ hostvars.keys() }} 
  with_items: "{{ groups['all']}}"
  register: pepe

- name: "fake loop"
  command: echo {{ item }}
  with_lines: grep jeronimog /etc/passwd   
  ignore_errors: True

- name: "daddasda33a"
  command: echo {{pepe}}


- name: "replacing test"
  ignore_errors: True
  run_once: True
  with_items:
    - { regexp: '^dog' ,  line: 'Hi' }
    - { regexp: '^cat' ,  line: 'you' }
  lineinfile:
    dest: /home/jeronimog/Projects/ansible/ansible2/testfile
    regexp: "{{ item.regexp }}"
    line: "{{ item.line}}"
    state: present
- name: "testing lambdas"
  command: echo {{item}}
  with_items: "{{ [1,2,3,4] | list }}"

- name: "testing library"
  jerry:
    testvar: [1,2,3,4]
  register: tl
- name: "test lookup"
    #msg: "{{tl['out']['temp']}}"
  command: echo {{item}}
  with_items: "{{tl['out']['someinfo']['testvar']}}"

#- name: "test replce simple"
  #replace:
    #dest: /home/jegarcia/Projects/ansible2/testfile
    #regexp: "{{ item.reg }}"
  #with_items:
    #- { reg: 'Dog,pepe' }
    #- { reg: 'Cat,pepe' }
    #2

     
- debug:
    msg: "{{ hostvars[inventory_hostname]['pepo'] }}"
##when: 
  ##- ct['rc'] == 0
  ##- " [ct['stdout'].rfind('h')] == map(lambda x: 0 if x == 0 else 1 , [0] )"
  ##- " [ct['stdout'].rfind('h')]|length == 1  "
  ##- " ct['stdout'] == 0 "
  ##- " 1 in [1,2,3,4] "
    #- "{{ groups['all'] }} "
    ##- " {{ ansible_all_ipv4_addresses }} "
    ##- [1,2]
    #register: output
    #- debug:
      #msg: 
        ##- "{{ct['stdout']}}"
        ##- " {{ hostvars['127.0.0.1']['ansible_connection']['local'] }}"
        ##- " {{ hostvars[inventory_hostname] }} "
        ##- " {{ groups['all'] }} "
        ##- " {{ output }} "
         #- " {{ groups['all'] }} "
